### ISSUE TITLE
Implement /cc comments on edits

### ISSUE THREAD

**Issue by xstefank** [xstefank/wildfly-github-bot#128]
We should have similarly changing comment for triage /cc comments as we have for format. So if the author changes the pr, e.g. by changing some new files that hit different rules, the /cc comment should be updated with new mentions.

**Comment by petrberan** [comment]
This issue is a direct contradiction to #104 . Should it be comments or review requests then?

**Comment by xstefank** [comment]
for now comments, 104 is considered long term just as an idea

**Comment by The-Huginn** [comment]
#104 should be implemented but waiting for the other PR to be closed, so I can rebase and open it for a review. I can add this functionality to it.

Currently, it requests people for PR review only if they are collaborators for that repo, otherwise it /cc comments the others. I can update it to add/remove people to their respective area, i.e. /cc comment or PR review request
